name: project
description: Project management — lint, format, and type-check workflows
commands:
  - name: lint
    description: Run code quality checks (no console.log, no 'any' types in library code)
    usage: "bun run lint"
  - name: format
    description: Check code formatting (spaces not tabs, consistent style)
    usage: "bun run format"
  - name: typecheck
    description: Run TypeScript type checker in strict mode (no emit)
    usage: "bun run typecheck"
  - name: test
    description: Run all unit tests
    usage: "bun test"
  - name: build
    description: Bundle the project for production
    usage: "bun run build"
