// smart-agent/src/types.ts
// All type definitions for the smart-agent package
import type { ToolErrorCode } from "./errors"

/** A built-in tool the agent can invoke */
export interface Tool {
    name: string
    description: string
    parameters: Record<string, { type: string; description: string; required?: boolean }>
    execute: (params: Record<string, any>) => Promise<ToolResult>
}

/** Result from a tool execution */
export interface ToolResult {
    success: boolean
    output: string
    error?: string
    /** Structured error classification — enables programmatic handling without string-parsing */
    errorCode?: ToolErrorCode
}

// Skills are .md files with YAML frontmatter, parsed by jsx-ai's parseSkillFile.
// See jsx-ai/src/skill.ts for the SkillMeta type.

/** An objective the agent must achieve */
export interface Objective {
    /** Identifier */
    name: string
    /** Human-readable description — injected into the system prompt */
    description: string
    /** Validator function — runs after each LLM turn to check if met */
    validate: (state: AgentState) => Promise<ObjectiveResult> | ObjectiveResult
}

/** Result of an objective validation */
export interface ObjectiveResult {
    met: boolean
    reason: string
}

/** Accumulated state across iterations */
export interface AgentState {
    /** All messages exchanged */
    messages: Message[]
    /** Current iteration number (0-based) */
    iteration: number
    /** All tool invocations and their results */
    toolHistory: ToolHistoryEntry[]
    /** Files that have been created/modified */
    touchedFiles: Set<string>
}

/** A tool invocation record */
export interface ToolHistoryEntry {
    iteration: number
    tool: string
    params: Record<string, any>
    result: ToolResult
}

/** A single message in the conversation */
export interface Message {
    role: "system" | "user" | "assistant" | "tool"
    content: string
    timestamp?: number
}

/** Tool invocation parsed from LLM response */
export interface ToolInvocation {
    tool: string
    params: Record<string, any>
    reasoning: string
}

/** Agent configuration */
export interface AgentConfig {
    /** LLM model identifier (e.g. "gemini-3-flash-preview", "gpt-4o") */
    model: string
    /** Skills — file paths to .md skill files (YAML frontmatter + markdown body) */
    skills?: string[]
    /** Objectives the agent must achieve. Optional when using Agent.plan() */
    objectives?: Objective[]
    /** Maximum loop iterations. Default: 20 */
    maxIterations?: number
    /** LLM temperature. Default: 0.3 */
    temperature?: number
    /** Max tokens per LLM call. Default: 8000 */
    maxTokens?: number
    /** Working directory for file/exec tools. Default: process.cwd() */
    cwd?: string
    /** Timeout per tool execution in ms. Default: 30000 */
    toolTimeoutMs?: number
    /** Additional system prompt text */
    systemPrompt?: string
    /** Custom tools to add alongside the 6 built-in ones */
    tools?: Tool[]
    /** AbortSignal to cancel the agent loop */
    signal?: AbortSignal
    /** Disable real-time streaming. Uses structured calls that return token usage data — ideal for batch benchmarking. */
    noStreaming?: boolean
    /** If true, blocks autonomous shell execution unless approved via onApproval callback. */
    safeMode?: boolean
    /**
     * Called when safeMode is ON and the agent wants to run a shell command.
     * Return `true` to approve, `false` to reject.
     * If not provided, safe mode blocks all exec calls with an error message.
     *
     * ```ts
     * onApproval: async (tool, params) => {
     *     const ok = await askUser(`Run "${params.command}"?`);
     *     return ok;
     * }
     * ```
     */
    onApproval?: (tool: string, params: Record<string, any>) => Promise<boolean> | boolean
    /**
     * Called with incremental output chunks during exec tool execution.
     * Useful for showing real-time command output in a UI.
     *
     * ```ts
     * onToolOutput: (tool, chunk) => process.stdout.write(chunk)
     * ```
     */
    onToolOutput?: (tool: string, chunk: string) => void
}

/** Serialized objective generated by the planner — uses templates instead of code */
export interface PlannedObjective {
    name: string
    description: string
    type: "file_exists" | "file_contains" | "command_succeeds" | "command_output_contains" | "custom_check" | "respond" | "task_scheduled"
    /** Parameters for the objective type */
    params: Record<string, string>
}

/** Events emitted during the agent loop */
export type AgentEvent =
    | { type: "iteration_start"; iteration: number; elapsed: number }
    | { type: "thinking"; iteration: number; message: string }
    | { type: "thinking_delta"; iteration: number; delta: string }
    | { type: "tool_start"; iteration: number; tool: string; params: Record<string, any> }
    | { type: "tool_result"; iteration: number; tool: string; result: ToolResult }
    | { type: "objective_check"; iteration: number; results: Array<{ name: string; met: boolean; reason: string }> }
    | { type: "planning"; objectives: PlannedObjective[] }
    | { type: "complete"; iteration: number; elapsed: number }
    | { type: "cancelled"; iteration: number; elapsed: number }
    | { type: "error"; iteration: number; error: string }
    | { type: "max_iterations"; iteration: number }
    | { type: "usage"; iteration: number; usage: { inputTokens: number; outputTokens: number; thinkingTokens?: number } }
    | { type: "approval_required"; iteration: number; tool: string; params: Record<string, any>; approved: boolean }
    | { type: "tool_output_delta"; iteration: number; tool: string; delta: string }


